#!/usr/bin/env node
/* Generates backend/supabase/seed/*.sql from the app's own JS data, so the
   database reference data can never drift from the demo:
     js/specialties.js         -> specialties (the shared RN specialty list)
     js/credential-catalog.js  -> jurisdictions, issuers, credential_catalog
     js/requirements.js        -> requirement_sets (WORK_TYPE, SPECIALTY, STATE) + requirements
     js/assignments.js         -> demo organizations, assignments, FACILITY override sets
     js/demo-data.js           -> demo clinicians + credentials (DEMO DATA)
   Usage: node backend/scripts/generate-seed.js   (from the repo root) */
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'../..');
const store={};const ctx={console,Date,Math,JSON,localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v)},removeItem:k=>{delete store[k]}},document:{getElementById:()=>null}};
vm.createContext(ctx);
for(const f of ['credential-model','specialties','credential-catalog','verification-registry','requirements','assignments','demo-data'])vm.runInContext(fs.readFileSync(path.join(root,'js',f+'.js'),'utf8'),ctx,{filename:f});
vm.runInContext('globalThis.__x={VERIFICATION_SOURCES,kindFloor,sourceLevel,REGISTRY_AS_OF,POLICY_VERSIONS,US_JURISDICTIONS,SPECIALTY_LIST:SPECIALTIES,SPECIALTY_PREFERRED,CREDENTIAL_CATALOG,CATALOG_AS_OF,WORK_TYPE_BASES,SPECIALTY_MODULES,SPECIALTIES:typeof SPECIALTIES!=="undefined"?SPECIALTIES:[],ORGANIZATIONS:typeof ORGANIZATIONS!=="undefined"?ORGANIZATIONS:[],ASSIGNMENT_DEFS:typeof ASSIGNMENT_DEFS!=="undefined"?ASSIGNMENT_DEFS:[],DEMO_SEED:typeof DEMO_SEED!=="undefined"?DEMO_SEED:[],DEMO_NURSES:typeof DEMO_NURSES!=="undefined"?DEMO_NURSES:[],DEMO_PROFILE:typeof DEMO_PROFILE!=="undefined"?DEMO_PROFILE:null,issuerFor,credentialDisplayName,credentialTypeCode,specialtyName}',ctx);
const X=ctx.__x;
const q=v=>v==null||v===''?'null':typeof v==='number'||typeof v==='boolean'?String(v):`'${String(v).replace(/'/g,"''")}'`;
const id=s=>`md5('veridun:${s}')::uuid`;
const J=X.US_JURISDICTIONS;
const issuerKind=k=>({STATE_BOARD:'STATE_BOARD'})[k.source]||(/^CERT_|QUAL_SPECIALTY/.test(k.kind)?'CERT_BODY':/^EMP_|^COMP_/.test(k.kind)?'EMPLOYER':/^HEALTH_/.test(k.kind)?'OCC_HEALTH':/^SCREEN_/.test(k.kind)?'SCREENING_VENDOR':/^EDU_|^QUAL_/.test(k.kind)?'SCHOOL':/^SKILLS_|^REF_/.test(k.kind)?'ATTESTATION':'OTHER');
const head=t=>`-- GENERATED by backend/scripts/generate-seed.js from the app's js/ data. Do not edit by hand.\n-- ${t}\n`;

/* ---------- reference seed ---------- */
let r=head('Reference data: specialties, jurisdictions, issuers, credential catalog, verification sources, platform requirement templates (demo templates).');
r+=`\nbegin;\n\ninsert into public.specialties (id, grp, name, short_name, sort_order) values\n`+X.SPECIALTY_LIST.map(sp=>` (${q(sp.id)}, ${q(sp.groupLabel)}, ${q(sp.name)}, ${q(sp.short)}, ${sp.sort})`).join(',\n')+`\non conflict (id) do update set grp = excluded.grp, name = excluded.name, short_name = excluded.short_name, sort_order = excluded.sort_order;\n`;
r+=`\ninsert into public.jurisdictions (code, name, board_name, nlc_status, as_of) values\n`+J.map(j=>` (${q(j.code)}, ${q(j.name)}, ${q(j.issuer)}, ${j.nlc?q(j.nlc):'null'}, ${q(X.CATALOG_AS_OF)})`).join(',\n')+`\non conflict (code) do update set name = excluded.name, board_name = excluded.board_name, nlc_status = excluded.nlc_status, as_of = excluded.as_of;\n`;
const issuers=new Map();J.forEach(j=>issuers.set(j.issuer+'|'+j.code,{name:j.issuer,kind:'STATE_BOARD',jur:j.code}));
X.CREDENTIAL_CATALOG.filter(k=>k.issuer&&k.source!=='STATE_BOARD').forEach(k=>{if(![...issuers.values()].some(i=>i.name===k.issuer&&!i.jur))issuers.set(k.issuer+'|',{name:k.issuer,kind:issuerKind(k),jur:null})});
r+=`\ninsert into public.issuers (name, kind, jurisdiction_code) values\n`+[...issuers.values()].map(i=>` (${q(i.name)}, ${q(i.kind)}, ${q(i.jur)})`).join(',\n')+`\non conflict (name, jurisdiction_code) do update set kind = excluded.kind;\n`;
r+=`\ninsert into public.credential_catalog (kind, label, short_label, category, section, privacy, jurisdiction_rule, source, default_issuer, recency_months, counts_for_readiness, keywords) values\n`+X.CREDENTIAL_CATALOG.map(k=>` (${q(k.kind)}, ${q(k.label)}, ${q(k.short)}, ${q(k.category)}, ${q(k.section)}, ${q(k.privacy)}, ${q(k.jurisdiction)}, ${q(k.source)}, ${q(k.issuer)}, ${q(k.recencyMonths)}, ${k.readiness!==false}, ${q(k.keywords)})`).join(',\n')+`\non conflict (kind) do update set label = excluded.label, short_label = excluded.short_label, category = excluded.category, section = excluded.section, privacy = excluded.privacy, jurisdiction_rule = excluded.jurisdiction_rule, source = excluded.source, default_issuer = excluded.default_issuer, recency_months = excluded.recency_months, counts_for_readiness = excluded.counts_for_readiness, keywords = excluded.keywords;\n`;
r+=`\ninsert into public.verification_sources (name, method, is_simulated, notes) values
 ('Simulated primary-source check (DEMO)', 'SIMULATED_PRIMARY_SOURCE', true, 'Demo only: no licensing board or issuer is contacted.'),
 ('Manual document review', 'MANUAL_DOCUMENT_REVIEW', false, 'Verifier reviews the private source document via a short-lived signed URL.'),
 ('Employer attestation', 'EMPLOYER_ATTESTATION', false, 'Employer / HR confirms dates and specialty.'),
 ('Clinician attestation', 'CLINICIAN_ATTESTATION', false, 'Skills checklists completed and attested by the clinician.')
on conflict (name) do nothing;\n`;
const reqRow=(setKey,kind,pref=false)=>{const k=X.CREDENTIAL_CATALOG.find(c=>c.kind===kind);return `((select id from public.requirement_sets where owner_org_id is null and ${setKey}), false, ${q(kind)}, null, 'ADD', ${q(k?.recencyMonths)}, ${q(k?.minMonths)}, ${pref}, ${pref?q('Preferred, not required'):'null'})`};
r+=`\n-- Platform requirement templates (DEMO TEMPLATES — not any real agency's or facility's requirements)\n`;
r+=`insert into public.requirement_sets (owner_org_id, layer, key, name, authority, is_demo_template) values\n`+[
 ...X.WORK_TYPE_BASES.map(w=>` (null, 'WORK_TYPE', ${q(w.id)}, ${q(w.name+' base set')}, ${q(w.name+' base set (demo template)')}, true)`),
 ...Object.keys(X.SPECIALTY_MODULES).map(s=>` (null, 'SPECIALTY', ${q(s)}, ${q(X.specialtyName(s)+' module')}, ${q(X.specialtyName(s)+' module (demo template)')}, true)`),
 ...J.map(j=>` (null, 'STATE', ${q(j.code)}, ${q(j.name+' RN authorization')}, ${q('State licensure · '+j.issuer)}, false)`)
].join(',\n')+`\non conflict (owner_org_id, layer, key) do update set name = excluded.name, authority = excluded.authority;\n`;
r+=`\ndelete from public.requirements where requirement_set_id in (select id from public.requirement_sets where owner_org_id is null);\n`;
r+=`insert into public.requirements (requirement_set_id, is_rn_authorization, kind, jurisdiction_code, action, recency_months, min_months, is_preferred, note) values\n`+[
 ...X.WORK_TYPE_BASES.flatMap(w=>w.kinds.map(k=>' '+reqRow(`layer = 'WORK_TYPE' and key = ${q(w.id)}`,k))),
 ...Object.entries(X.SPECIALTY_MODULES).flatMap(([s,ks])=>ks.map(k=>' '+reqRow(`layer = 'SPECIALTY' and key = ${q(s)}`,k))),
 ...Object.entries(X.SPECIALTY_PREFERRED).flatMap(([s,ks])=>ks.map(k=>' '+reqRow(`layer = 'SPECIALTY' and key = ${q(s)}`,k,true))),
 ...J.map(j=>` ((select id from public.requirement_sets where owner_org_id is null and layer = 'STATE' and key = ${q(j.code)}), true, null, ${q(j.code)}, 'ADD', null, null, false, 'Single-state license here, or a multistate license whose privilege is honored here (NLC)')`)
].join(',\n')+`;\n\ncommit;\n`;
fs.writeFileSync(path.join(root,'backend/supabase/seed/01_reference.sql'),r);

/* ---------- verification source registry (PR 13) ---------- */
const legacyMethod=s=>s.id==='nursys-enotify'?'PRIMARY_SOURCE_API':s.method==='EMPLOYER'?'EMPLOYER_ATTESTATION':s.method==='SELF_ATTESTED'?'CLINICIAN_ATTESTATION':'MANUAL_DOCUMENT_REVIEW';
const arr=a=>`array[${(a||[]).map(q).join(',')}]::text[]`;
let v=head('Verification Source Registry (js/verification-registry.js), catalog verification floors, and policy metadata for platform templates. Safe to re-run.');
v+=`\nbegin;\n\ninsert into public.verification_sources (name, method, is_simulated, notes, lookup_url, slug, source_type, jurisdiction_code, covered_jurisdictions, credential_kinds, source_method, grants_level, api_available, api_requirements, status, monitoring, nursys_participating, as_of) values\n`+
 X.VERIFICATION_SOURCES.map(s=>` (${q(s.name)}, ${q(legacyMethod(s))}, false, ${q(s.notes)}, ${q(s.lookupUrl)}, ${q(s.id)}, ${q(s.type)}, ${s.type==='LICENSING_BOARD'?q(s.jurisdiction):'null'}, ${arr(s.jurisdictions)}, ${arr(s.kinds)}, ${q(s.method)}, ${q(X.sourceLevel(s))}, ${!!s.api.available}, ${q(s.api.requirements)}, ${q(s.status)}, ${!!s.monitoring}, ${s.type==='LICENSING_BOARD'?String(!!s.nursys):'null'}, ${q(X.REGISTRY_AS_OF)})`).join(',\n')+
 `\non conflict (name) do update set method = excluded.method, is_simulated = false, notes = excluded.notes, lookup_url = excluded.lookup_url, slug = excluded.slug, source_type = excluded.source_type, jurisdiction_code = excluded.jurisdiction_code, covered_jurisdictions = excluded.covered_jurisdictions, credential_kinds = excluded.credential_kinds, source_method = excluded.source_method, grants_level = excluded.grants_level, api_available = excluded.api_available, api_requirements = excluded.api_requirements, status = excluded.status, monitoring = excluded.monitoring, nursys_participating = excluded.nursys_participating, as_of = excluded.as_of;\n`;
v+=`update public.verification_sources set status = 'UNAPPROVED' where slug is null;\n`;
v+=`\nupdate public.credential_catalog c set min_verification_level = x.lvl, level_floor_locked = x.locked, level_basis = x.basis from (values\n`+X.CREDENTIAL_CATALOG.map(k=>{const f=X.kindFloor(k.kind);return` (${q(k.kind)}, ${q(f.level)}, ${f.locked}, ${q(f.basis)})`}).join(',\n')+`\n) as x(kind, lvl, locked, basis) where c.kind = x.kind;\n`;
v+=`\nupdate public.requirement_sets set policy_code = 'VDN-' || key || '-BASE', policy_version = ${q(X.POLICY_VERSIONS.WORK_TYPE.version)}, effective_on = ${q(X.POLICY_VERSIONS.WORK_TYPE.effective)}, required_by = authority where owner_org_id is null and layer = 'WORK_TYPE';\n`;
v+=`update public.requirement_sets set policy_code = 'VDN-SPEC-' || key, policy_version = ${q(X.POLICY_VERSIONS.SPECIALTY.version)}, effective_on = ${q(X.POLICY_VERSIONS.SPECIALTY.effective)}, required_by = authority where owner_org_id is null and layer = 'SPECIALTY';\n`;
v+=`update public.requirement_sets set policy_code = 'STATE-' || replace(key, 'US-', '') || '-RN-AUTH', policy_version = ${q(X.CATALOG_AS_OF)}, required_by = authority where owner_org_id is null and layer = 'STATE';\n`;
v+=`update public.requirements r set min_verification_level = case when r.is_rn_authorization then 'PRIMARY_SOURCE_VERIFIED' else c.min_verification_level end,
  validity_rule = case when r.is_rn_authorization then 'Must authorize RN practice in the assignment state and stay active through the assignment end'
    when r.recency_months is not null then 'At least ' || coalesce(r.min_months, r.recency_months) || ' months of this specialty in the ' || r.recency_months || ' months before the start date'
    else 'Must stay valid through the assignment end' end
from public.requirement_sets s, public.credential_catalog c
where s.id = r.requirement_set_id and s.owner_org_id is null and (c.kind = r.kind or (r.is_rn_authorization and c.kind = 'RN_LICENSE'));\n`;
v+=`\ncommit;\n`;
fs.writeFileSync(path.join(root,'backend/supabase/seed/03_verification_registry.sql'),v);

/* ---------- demo seed ---------- */
let d=head('DEMO DATA ONLY (fictional people, agencies and facilities). For local/dev databases — do not load into production.\n-- Creates demo auth users with no password (cannot sign in until you set one in the Supabase dashboard).\n-- Dates are relative to current_date, like the browser demo.');
d+=`\nbegin;\n\n`;
const users=[['alex','alex.morgan@demo.veridun.invalid','Alex Morgan','clinician'],['jordan','jordan.rivera@demo.veridun.invalid','Jordan Rivera','clinician'],['sam','sam.okafor@demo.veridun.invalid','Sam Okafor','clinician'],
 ...X.ORGANIZATIONS.map(o=>[`recruiter-${o.id}`,`recruiter.${o.id}@demo.veridun.invalid`,`${o.name} recruiter (demo)`,'org_member']),['verifier','verifier@demo.veridun.invalid','Demo Verifier','verifier']];
d+=`insert into auth.users (id, instance_id, aud, role, email, raw_app_meta_data, raw_user_meta_data, created_at, updated_at) values\n`+users.map(([k,e])=>` (${id('user:'+k)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(e)}, '{"provider":"email","providers":["email"]}', '{"demo":true}', now(), now())`).join(',\n')+`\non conflict (id) do nothing;\n`;
d+=`insert into public.users (id, email, display_name, role) values\n`+users.map(([k,e,n,role])=>` (${id('user:'+k)}, ${q(e)}, ${q(n)}, ${q(role)})`).join(',\n')+`\non conflict (id) do update set display_name = excluded.display_name, role = excluded.role;\n\n`;
const nurses=X.DEMO_NURSES.map(n=>n.live?{...n,secondarySpecialties:n.secondarySpecialties||X.DEMO_PROFILE?.secondarySpecialties||[],seed:X.DEMO_SEED.map(([k,j,days,req,x])=>[k,j,days,x])}:n);
d+=`insert into public.clinicians (id, user_id, full_name, post_nominals, specialty, secondary_specialties, home_jurisdiction, is_demo) values\n`+nurses.map(n=>` (${id('clinician:'+n.id)}, ${id('user:'+n.id)}, ${q(n.name)}, ${q(n.credentials)}, ${q(n.specialty)}, array[${(n.secondarySpecialties||[]).map(q).join(',')}]::text[], ${q(n.homeState)}, true)`).join(',\n')+`\non conflict (id) do nothing;\n\n`;
d+=`insert into public.organizations (id, slug, name, org_type, is_demo) values\n`+X.ORGANIZATIONS.map(o=>` (${id('org:'+o.id)}, ${q(o.id)}, ${q(o.name)}, ${q(o.type)}, true)`).join(',\n')+`\non conflict (id) do nothing;\n`;
d+=`insert into public.organization_members (org_id, user_id, role) values\n`+X.ORGANIZATIONS.map(o=>` (${id('org:'+o.id)}, ${id('user:recruiter-'+o.id)}, 'recruiter')`).join(',\n')+`\non conflict do nothing;\n\n`;
d+=`-- Facility override layers (owned by the agency)\n`;
X.ASSIGNMENT_DEFS.filter(a=>(a.overrides?.add||[]).length||(a.overrides?.waive||[]).length).forEach(a=>{
 d+=`insert into public.requirement_sets (id, owner_org_id, layer, key, name, authority, is_demo_template) values (${id('set:facility:'+a.id)}, ${id('org:'+a.orgId)}, 'FACILITY', ${q(a.id)}, ${q('Facility overrides · '+a.facility)}, ${q('Facility override · '+a.facility)}, true) on conflict do nothing;\n`;
 const rows=[...(a.overrides.add||[]).map(k=>[k,'ADD']),...(a.overrides.waive||[]).map(k=>[k,'WAIVE'])];
 d+=`delete from public.requirements where requirement_set_id = ${id('set:facility:'+a.id)};\n`;
 d+=`insert into public.requirements (requirement_set_id, kind, action, note) values `+rows.map(([k,act])=>`(${id('set:facility:'+a.id)}, ${q(k)}, ${q(act)}, ${q(a.overrides.note)})`).join(', ')+`;\n`;
});
d+=`\ninsert into public.assignments (id, org_id, slug, name, work_type, jurisdiction_code, facility_name, starts_on, ends_on, accepted_specialties, status, is_demo) values\n`+X.ASSIGNMENT_DEFS.map(a=>` (${id('assignment:'+a.id)}, ${id('org:'+a.orgId)}, ${q(a.id)}, ${q(a.name)}, ${q(a.workType)}, ${q(a.jurisdiction)}, ${q(a.facility)}, current_date + ${a.startInDays}, current_date + ${a.startInDays+a.weeks*7}, array[${a.specialties.map(q).join(',')}], 'PUBLISHED', true)`).join(',\n')+`\non conflict (id) do nothing;\n`;
d+=`insert into public.assignment_requirements (assignment_id, requirement_set_id)\n`+X.ASSIGNMENT_DEFS.map(a=>{const sets=[`(owner_org_id is null and layer = 'STATE' and key = ${q(a.jurisdiction)})`,`(owner_org_id is null and layer = 'WORK_TYPE' and key = ${q(a.workType)})`,...a.specialties.map(s=>`(owner_org_id is null and layer = 'SPECIALTY' and key = ${q(s)})`)];if((a.overrides?.add||[]).length||(a.overrides?.waive||[]).length)sets.push(`id = ${id('set:facility:'+a.id)}`);return ` select ${id('assignment:'+a.id)}, id from public.requirement_sets where ${sets.join(' or ')}`}).join('\n union all\n')+`\non conflict do nothing;\n\n`;
d+=`-- Demo credentials (VERIFIED by the simulated source — DEMO, not a real verification)\n`;
d+=`insert into public.credentials (id, clinician_id, kind, type_code, display_name, jurisdiction_code, issuer_id, status, expires_on, metadata, verified_at, last_monitored_at) values\n`+nurses.flatMap(n=>n.seed.map(([kind,jur,days,x],i)=>{const iss=X.issuerFor(kind,jur);const md=x&&x.years!=null?`jsonb_build_object('years', ${x.years}, 'last_worked_on', current_date + ${x.lastWorkedDays||0})`:`'{}'::jsonb`;
 return ` (${id(`cred:${n.id}:${i}`)}, ${id('clinician:'+n.id)}, ${q(kind)}, ${q(X.credentialTypeCode(kind,jur))}, ${q(x?.name||X.credentialDisplayName(kind,jur))}, ${q(jur)}, (select id from public.issuers where name = ${q(iss)} and jurisdiction_code is not distinct from ${jur?q(jur):'null'} limit 1), 'VERIFIED', ${days==null?'null':`current_date + ${days}`}, ${md}, now() - interval '1 day', now() - interval '1 day')`})).join(',\n')+`\non conflict (id) do nothing;\n`;
d+=`insert into public.credential_verifications (credential_id, source_id, method, outcome, started_at, completed_at, duration_ms, manual_intervention, notes)
select c.id, (select id from public.verification_sources where method = 'SIMULATED_PRIMARY_SOURCE' limit 1), 'SIMULATED_PRIMARY_SOURCE', 'SUCCEEDED',
       now() - interval '1 day', now() - interval '1 day', 0, false, 'DEMO SEED (not a real verification)'
  from public.credentials c join public.clinicians k on k.id = c.clinician_id
 where k.is_demo and not exists (select 1 from public.credential_verifications v where v.credential_id = c.id);\n\n`;
d+=`insert into public.audit_events (event_type, actor_type, clinician_id, result, detail)
select 'DEMO_SEEDED', 'SYSTEM', k.id, 'DEMO', jsonb_build_object('credentials', (select count(*) from public.credentials c where c.clinician_id = k.id))
  from public.clinicians k where k.is_demo
   and not exists (select 1 from public.audit_events e where e.event_type = 'DEMO_SEEDED' and e.clinician_id = k.id);\n\ncommit;\n`;
fs.writeFileSync(path.join(root,'backend/supabase/seed/02_demo.sql'),d);
console.log('wrote seed/01_reference.sql ('+X.SPECIALTY_LIST.length+' specialties, '+J.length+' jurisdictions, '+X.CREDENTIAL_CATALOG.length+' kinds, '+issuers.size+' issuers) and seed/02_demo.sql ('+nurses.length+' clinicians, '+X.ASSIGNMENT_DEFS.length+' assignments)');
