/* Clinician workspace: Home, Passport, Tasks, Opportunities, onboarding dialog. */
function setBusy(s){$('busy').textContent=s||''}
function render(){creds=creds.map(v81Normalize);const ob=onboarding();$('onboardPct').textContent=ob.pct+'%';$('vcount').textContent=creds.filter(c=>c.primary==='VERIFIED').length;$('acount').textContent=creds.filter(c=>c.chain==='ACCEPTED').length;$('ncount').textContent=creds.filter(c=>['UNVERIFIED','VERIFYING'].includes(c.primary)||c.chain==='SECURING').length;$('onboardBar').style.width=ob.pct+'%';$('onboardSummaryText').textContent=`${ob.ok} of ${ob.req.length} required items satisfied`;$('readyBadge').textContent=ob.ready?'ONBOARDING READY':'IN PROGRESS';$('readyBadge').className='badge '+(ob.ready?'READY':'PENDING');let a=filter==='all'?creds:creds.filter(c=>c.section===filter);$('empty').classList.toggle('hidden',a.length>0);$('tbl').classList.toggle('hidden',!a.length);$('rows').innerHTML=a.map(c=>{let z=`<button class="mini details" data-id="${c.id}">Details</button>`;if(c.primary==='UNVERIFIED')z+=`<button class="mini verify" data-id="${c.id}">Submit for Verification</button>`;if(c.primary==='VERIFYING')z+=`<button class="mini" disabled>Verification in Progress</button>`;if(eligible(c))z+=`<button class="mini chainbtn issue" data-id="${c.id}">Secure Credential</button>`;if(c.chain==='SECURING')z+=`<button class="mini goodbtn accept" data-id="${c.id}">Accept</button>`;if(['SECURING','ACCEPTED'].includes(c.chain))z+=`<button class="mini showproof" data-id="${c.id}">XRPL Proof</button>`;z+=`<button class="mini del" data-id="${c.id}">Delete</button>`;let prov=c.prov?.verifiedAt?`${ec(c.prov.source)}<div class="source">${ec(c.prov.method)} · ${new Date(c.prov.verifiedAt).toLocaleDateString()}</div>`:'Not yet verified';return `<tr><td><b>${ec(c.name)}</b>${c.privateOnly?'<div class="small">Private/off-chain only</div>':''}</td><td class="mono">${ec(c.type)}</td><td>${c.required?'<span class="badge REQ">REQUIRED</span>':'Optional'}</td><td><span class="badge ${cls(c.primary)}">${ec(c.primary)}</span></td><td><span class="badge ${userChainClass(c)}">${ec(userChain(c))}</span></td><td>${fd(c.expiration)}</td><td>${prov}</td><td><div class="rowact">${z}</div></td></tr>`}).join('');document.querySelectorAll('.verify').forEach(b=>b.onclick=()=>openVerify(+b.dataset.id));document.querySelectorAll('.issue').forEach(b=>b.onclick=()=>issue(+b.dataset.id));document.querySelectorAll('.accept').forEach(b=>b.onclick=()=>accept(+b.dataset.id));document.querySelectorAll('.showproof,.details').forEach(b=>b.onclick=()=>showProof(+b.dataset.id));document.querySelectorAll('.del').forEach(b=>b.onclick=()=>{creds=creds.filter(c=>c.id!=b.dataset.id);save();render()});renderV7Views()}
function showV7View(id){
 document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));
 document.querySelectorAll('.v7nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));
 window.scrollTo({top:0,behavior:'smooth'});
 if(id==='passportView'||id==='tasksView'||id==='opportunitiesView')renderV7Views()
}
function renderV7Views(){
 const ready=v7Readiness();if($('v7PassportReady'))$('v7PassportReady').textContent=ready+'%';
 const passCats=['Licenses','Certifications','Education','Employment & HR','Clinical Qualifications'];
 if($('v7PassportSections'))$('v7PassportSections').innerHTML=passCats.map(cat=>{
   const arr=creds.filter(c=>catFor(c)===cat&&c.primary==='VERIFIED'&&c.prov?.active);
   if(!arr.length)return'';
   return `<div class="task-category-v7"><div class="cathead"><b>${ec(cat==='Employment & HR'?'Employment Experience':cat)}</b></div>${arr.map(c=>`<div class="passport-item-v7"><div><b>✓ ${ec(c.name)}</b><div class="small">${ec(c.prov?.source||'Verified source')}</div></div><div><span class="badge ${userChainClass(c)}">${ec(userChain(c))}</span> <button class="mini details" data-id="${c.id}">View</button></div></div>`).join('')}</div>`
 }).join('');
 const cats=['Licenses','Certifications','Education','Employment & HR','Employee Health','Clinical Qualifications','Background & Screening','Submitted Credentials'];
 if($('v7TaskCategories'))$('v7TaskCategories').innerHTML=cats.map(cat=>{
   const arr=creds.filter(c=>catFor(c)===cat),verified=arr.filter(c=>c.primary==='VERIFIED').length,exp=arr.filter(c=>c.primary==='EXPIRING').length,missing=arr.filter(c=>['UNVERIFIED','EXPIRED','REVOKED'].includes(c.primary)).length;
   return `<div class="task-category-v7"><div class="cathead"><b>${ec(cat)}</b><div class="counts"><span class="chip">${arr.length} items</span><span class="chip">${verified} verified</span><span class="chip">${exp} expiring</span><span class="chip">${missing} missing/action</span></div></div>${arr.map(c=>`<div class="task-item-v7"><div><b>${ec(c.name)}</b><div class="small">${ec(c.primary)}${c.expiration?' · '+fd(c.expiration):''}</div></div><button class="mini details" data-id="${c.id}">${c.primary==='EXPIRING'?'Renew':'Open'}</button></div>`).join('')}</div>`
 }).join('');
 const a=[['RN_CA_ACTIVE','CA RN'],['CERT_ACLS','ACLS'],['CERT_BLS','BLS'],['CERT_CCRN','CCRN'],['EMP_ICU_VERIFIED','ICU experience']];
 const b=[['RN_MA_ACTIVE','Massachusetts RN'],['CERT_ACLS','ACLS'],['CERT_BLS','BLS'],['CERT_CCRN','CCRN'],['EMP_ICU_VERIFIED','ICU experience']];
 function opp(list,scoreId,reqId,btnId){const ok=list.filter(x=>v7ReqMatch(x[0])).length;$(scoreId).textContent=`${ok}/${list.length}`;$(reqId).innerHTML=list.map(x=>`<li>${v7ReqMatch(x[0])?'✓':'○'} ${ec(x[1])}</li>`).join('');$(btnId).textContent=ok===list.length?'Ready to Apply':'Complete Requirement'}
 if($('v7Opp1Score'))opp(a,'v7Opp1Score','v7Opp1Reqs','v7Opp1Action');
 if($('v7Opp2Score'))opp(b,'v7Opp2Score','v7Opp2Reqs','v7Opp2Action');
 document.querySelectorAll('.details').forEach(btn=>btn.onclick=()=>showProof(+btn.dataset.id))
}
function openOnboard(){const ob=onboarding();$('onboardRows').innerHTML=ob.req.map(c=>`<div class="reqrow"><div><b>${ec(c.name)}</b><div class="source">${ec(c.prov?.source||'Primary source pending')}</div></div><span class="badge ${reqSatisfied(c)?'READY':'PENDING'}">${reqSatisfied(c)?'SATISFIED':'PENDING'}</span></div>`).join('');$('onboard').showModal()}
function v81SyncAddForm(){const k=$('credentialKindV81').value;$('jurisdictionRowV81').classList.toggle('hidden',k!=='RN_LICENSE');$('otherRowV81').classList.toggle('hidden',k!=='OTHER');$('sec').value=k==='EDU_BSN'?'Clinical Requirements':k==='EMP_ICU_VERIFIED'?'Screening & Employment':k==='OTHER'?$('sec').value:'Licenses & Certifications'}
