/* Organization workspace (DEMO DATA). */
function v81RoleContext(){const b=v81Assignment(V81_ASSIGNMENTS[0]),ev=v81Events(),pending=creds.filter(c=>['UNVERIFIED','VERIFYING'].includes(c.primary)),med=v81Median(v81Durations());const exp=creds.filter(c=>{const d=c.official_expiration_date||c.expiration;if(!d)return false;return Math.ceil((new Date(d)-new Date())/86400000)<=90}).length;return{b,ev,pending,med,exp}}
function v81RenderOrganization(x){const{b,ev,pending,med,exp}=x;
if($('orgReadyV81'))$('orgReadyV81').textContent=b.ready?1:0;if($('orgMissingOneV81'))$('orgMissingOneV81').textContent=b.missing.length===1?1:0;if($('orgAwaitV81'))$('orgAwaitV81').textContent=pending.length;if($('orgExpV81'))$('orgExpV81').textContent=exp;if($('orgMedV81'))$('orgMedV81').textContent=v81Fmt(med);if($('orgReuseV81'))$('orgReuseV81').textContent='92%';
if($('orgSummaryV81'))$('orgSummaryV81').innerHTML=`<div class="row-v81"><div><b>Alex Morgan, RN, BSN, CCRN</b><div class="small">ICU · Boston Travel ICU</div></div><div><b>${b.ok}/${b.total} Ready</b><div class="small">${b.ready?'Assignment Ready':'Missing: '+b.missing.join(', ')}</div></div></div><div class="row-v81"><div><b>Jamie Smith</b><div class="small">ICU</div></div><b>11/12 Ready</b></div><div class="row-v81"><div><b>Taylor Reed</b><div class="small">PCU</div></div><b>8/12 Ready</b></div>`;
if($('orgBostonV81'))$('orgBostonV81').innerHTML=`<div class="${b.ready?'good-v81':'alert-v81'}"><b>${b.ready?'12/12 Requirements Satisfied — Assignment Ready':'11/12 Ready'}</b><div style="margin-top:4px">${b.ready?'All mandatory requirements satisfied.':'Missing: '+b.missing.join(', ')}</div></div>`;
if($('orgCandidatesBodyV81'))$('orgCandidatesBodyV81').innerHTML=`<table class="v81-table"><tr><th>Candidate</th><th>Specialty</th><th>Boston ICU</th><th>Status</th></tr><tr><td>Alex Morgan</td><td>ICU</td><td>${b.ok}/${b.total}</td><td>${b.ready?'Assignment Ready':'Missing '+b.missing.length}</td></tr><tr><td>Jamie Smith</td><td>ICU</td><td>11/12</td><td>Missing 1</td></tr><tr><td>Taylor Reed</td><td>PCU</td><td>8/12</td><td>Needs Attention</td></tr></table>`;
if($('orgAssignmentsBodyV81'))$('orgAssignmentsBodyV81').innerHTML=V81_ASSIGNMENTS.map(a=>{const r=v81Assignment(a);return`<div class="row-v81"><div><b>${a.name}</b><div class="small">${a.start} → ${a.end}</div></div><div><b>${r.ok}/${r.total}</b><div class="small">${r.ready?'Ready':r.missing.length+' missing'}</div></div></div>`}).join('');
if($('orgRequirementsBodyV81'))$('orgRequirementsBodyV81').innerHTML=['Travel ICU RN','Strike ICU RN','Rapid Response RN','Per-Diem RN'].map(n=>`<div class="row-v81"><div><b>${n}</b><div class="small">Reusable demo requirement template</div></div><button class="sec">View</button></div>`).join('');
if($('orgAnalyticsBodyV81'))$('orgAnalyticsBodyV81').innerHTML=`<table class="v81-table"><tr><td>Median verification time</td><td><b>${v81Fmt(med)}</b></td></tr><tr><td>Audit events</td><td><b>${ev.length}</b></td></tr><tr><td>Credential reuse rate</td><td><b>92%</b></td></tr></table><p class="small">DEMO DATA — NOT PRODUCTION RESULTS.</p>`;}
