/* Verification Console workspace (handoff §41). SIMULATED primary-source
   checks, rule-derived mismatch alerts, manual review, monitoring,
   revocations and the audit log. Metrics come from the event log and the
   current demo data. */
const AUDIT_GROUPS={VERIF:/^(VERIFICATION_|SOURCE_CHECK|MANUAL_REVIEW|CLASSIFICATION)/,MONITOR:/^(MONITORING_|CREDENTIAL_(REVOKED|REINSTATED|EXPIRED))/,SHARE:/^SHARE_/,ASSIGN:/^ASSIGNMENT_/,REF:/^(REFERENCE_|SHARE_REFERENCES)/,CRED:/^(CREDENTIAL_UPLOADED|CREDENTIAL_RENEWED|DEMO_SEEDED)/};
function auditRowHtml(e){const c=e.credential_id?creds.find(x=>x.id===e.credential_id):null;return`<div class="row-v81" style="display:block"><b>${ec(e.event_type)}</b><div class="small">${ec(activityText(e))}</div><div class="small">${new Date(e.timestamp).toLocaleString()} · ${ec(e.actor_type)}${e.verification_method?' · '+ec(e.verification_method):''}${c?' · '+ec(credLabel(c)):''}</div></div>`}
function alertHtml(a,withAction){return`<div class="alert-row-v85"><div><span class="layer-tag-v84 sev-${a.severity}">${a.severity}</span> <b>${ec(credLabel(a.c))}</b> <span class="small">· ${ec(a.rule)}</span></div><div class="small" style="margin-top:4px">${ec(a.text)}</div>${withAction&&['VERIFYING','UNVERIFIED'].includes(a.c.primary)?`<button class="mini" style="margin-top:6px" onclick="document.querySelector('.verifyTab[data-target=verifyManualV85]').click()">Open Manual Review</button>`:''}</div>`}
function v81RenderVerifier(x){const{ev,pending,med}=x;
 if($('verifySourcesBodyV13')&&!$('verifySourcesBodyV13').innerHTML)renderRegistryV13();
 if(typeof renderExtractionPanelV14==='function')renderExtractionPanelV14();
 if(typeof renderRefCallsV146==='function')renderRefCallsV146();
 const n=t=>ev.filter(e=>e.event_type===t).length,success=n('VERIFICATION_SUCCEEDED'),failed=n('VERIFICATION_FAILED'),manual=ev.filter(e=>e.manual_intervention).length,revoked=n('CREDENTIAL_REVOKED'),alerts=mismatchAlerts();
 const set=(id,v)=>{if($(id))$(id).textContent=v};
 set('verPendingV81',pending.length);set('verSuccessV81',success);set('verManualV81',creds.filter(needsManualReview).length);if($('verManualDoneV85'))$('verManualDoneV85').textContent=(n('MANUAL_REVIEW_APPROVED')+n('MANUAL_REVIEW_REJECTED'))+' completed';set('verFailedV81',failed);set('verMedianV81',v81Fmt(med));set('verMonitorV82',fmtPct(monitoringCoverage()));set('verMismatchV85',alerts.length);set('verRevokedV85',revoked);
 const flagged=new Set(alerts.map(a=>a.c.id));
 const q=pending.length?pending.map(c=>`<div class="row-v81"><div><b>${ec(credLabel(c))}</b><div class="small">${ec(c.kind)}${c.jurisdiction?' · '+ec(c.jurisdiction):''}</div>${queueRouteHtml(c)}${flagged.has(c.id)?'<div class="small" style="color:#9a3412">⚠ Mismatch alert — needs manual review</div>':''}</div>${flagged.has(c.id)?`<button class="sec" onclick="document.querySelector('.verifyTab[data-target=verifyManualV85]').click()">Open Manual Review</button>`:`<div class="verify-act-v147">${isRnLicense(c)?`<label class="small orig-issue-in-v147">Original issue date from the state board <span class="small">(optional · demo)</span><input type="date" class="origIssueV147" id="origIssueV147-${c.id}"></label>`:''}<button class="pri v81Verify" data-id="${c.id}">Run Simulated Primary-Source Check</button></div>`}</div>`).join(''):'<div class="small">Queue is clear.</div>';
 if($('verifyQueuePreviewV81'))$('verifyQueuePreviewV81').innerHTML=q;if($('verifyQueueBodyV81'))$('verifyQueueBodyV81').innerHTML=q;
 const al=alerts.length?alerts.map(a=>alertHtml(a,true)).join(''):'<div class="small">No mismatches. Rules checked: multistate license vs primary state of residence, verified-but-expired, expired at submission, unclassified type, duplicate records.</div>';
 if($('verifyMismatchPreviewV85'))$('verifyMismatchPreviewV85').innerHTML=al;if($('verifyMismatchBodyV85'))$('verifyMismatchBodyV85').innerHTML=al;
 const mr=pending.filter(c=>flagged.has(c.id));
 if($('verifyManualBodyV85'))$('verifyManualBodyV85').innerHTML=(mr.length?mr.map(c=>`<div class="alert-row-v85"><b>${ec(credLabel(c))}</b><div class="small">${ec(c.kind)}${c.jurisdiction?' · '+ec(c.jurisdiction):''} · submitted ${c.prov?.lastMonitored?fmtDT(c.prov.lastMonitored):'—'}</div>${alerts.filter(a=>a.c.id===c.id).map(a=>`<div class="small" style="margin-top:4px"><span class="layer-tag-v84 sev-${a.severity}">${a.severity}</span> ${ec(a.text)}</div>`).join('')}<div class="actions" style="margin-top:8px"><button class="pri" onclick="manualReviewDecision(${c.id},true)">Approve after review (simulated check)</button><button class="sec" onclick="manualReviewDecision(${c.id},false)">Reject</button></div></div>`).join(''):'<div class="small">No credentials need manual review.</div>')+`<p class="small">Every console action counts as a manual touch (${manual} this session). DEMO.</p>`;
 const lastRun=[...ev].reverse().find(e=>e.event_type==='MONITORING_RUN'),ver=creds.filter(c=>c.primary==='VERIFIED');
 if($('verifyMonitorBodyV85'))$('verifyMonitorBodyV85').innerHTML=`<div class="small" style="margin-bottom:8px">Coverage: <b>${fmtPct(monitoringCoverage())}</b> of verified credentials monitored in the last 30 days · last run: <b>${lastRun?fmtDT(lastRun.timestamp)+' ('+ec(lastRun.result)+')':'not run this session'}</b></div><button class="pri" id="runMonitorV85" onclick="runMonitoringCheck()">Run Monitoring Check (simulated)</button><table class="v81-table" style="margin-top:10px"><tr><th>Credential</th><th>Last monitored</th><th>Expires</th><th>Status</th><th></th></tr>${ver.map(c=>`<tr><td>${ec(credLabel(c))}</td><td>${c.prov?.lastMonitored?fmtDT(c.prov.lastMonitored):'—'}</td><td>${fd(credExpiry(c))||'—'}</td><td>${verificationBadgeHtml(c)}</td><td>${isRnLicense(c)||catFor(c)==='Certifications'?`<button class="mini" onclick="simulateRevocation(${c.id})">Simulate revocation</button>`:''}</td></tr>`).join('')}</table><p class="small">Simulated: a production system would poll boards and issuers (e.g. Nursys e-Notify) on a schedule. No real source is contacted.</p>`;
 const rc=creds.filter(c=>c.primary==='REVOKED'),proofRev=creds.filter(c=>c.chain==='REVOKED').length,shareRev=n('SHARE_REVOKED');
 if($('verifyRevokeBodyV85'))$('verifyRevokeBodyV85').innerHTML=`<table class="v81-table"><tr><td>Credential revocations (issuer, simulated)</td><td><b>${revoked}</b></td></tr><tr><td>Reinstatements</td><td><b>${n('CREDENTIAL_REINSTATED')}</b></td></tr><tr><td>XRPL Devnet proof revocations</td><td><b>${proofRev}</b></td></tr><tr><td>Passport access revoked by clinicians</td><td><b>${shareRev}</b></td></tr></table>${rc.map(c=>`<div class="alert-row-v85"><b>${ec(credLabel(c))}</b> ${verificationBadgeHtml(c)}<div class="small">Revoked ${fmtDT(c.prov?.revokedAt)} · readiness and shared assertions now show NOT CURRENT</div><button class="mini" style="margin-top:6px" onclick="reinstateCredential(${c.id})">Reinstate (simulated re-check)</button></div>`).join('')||'<div class="small" style="margin-top:8px">No revoked credentials.</div>'}`;
 const f=$('auditFilterV85')?.value||'all',aud=ev.filter(e=>f==='all'||AUDIT_GROUPS[f]?.test(e.event_type)).slice().reverse();
 if($('verifyAuditBodyV81'))$('verifyAuditBodyV81').innerHTML=aud.slice(0,50).map(auditRowHtml).join('')||'<div class="small">No events yet.</div>';
 if($('auditFilterV85')&&!$('auditFilterV85').onchange)$('auditFilterV85').onchange=()=>v81RenderRoles();
 if($('verifyAuditPreviewV85'))$('verifyAuditPreviewV85').innerHTML=ev.slice().reverse().slice(0,5).map(auditRowHtml).join('')||'<div class="small">No events yet.</div>';
 if($('verifyAnalyticsBodyV81'))$('verifyAnalyticsBodyV81').innerHTML=`<table class="v81-table"><tr><td>Verification successes</td><td>${success}</td></tr><tr><td>Median verification time</td><td>${v81Fmt(med)}</td></tr><tr><td>Manual reviews (touches)</td><td>${manual}</td></tr><tr><td>Approved / rejected after review</td><td>${n('MANUAL_REVIEW_APPROVED')} / ${n('MANUAL_REVIEW_REJECTED')}</td></tr><tr><td>Failed attempts</td><td>${failed}</td></tr><tr><td>Monitoring runs</td><td>${n('MONITORING_RUN')}</td></tr><tr><td>Revocations / reinstatements</td><td>${revoked} / ${n('CREDENTIAL_REINSTATED')}</td></tr><tr><td>Sample size</td><td>${ev.length} events</td></tr></table><p class="small">DEMO DATA — NOT PRODUCTION RESULTS. No accuracy claim is made without ground-truth review.</p>`;
 document.querySelectorAll('.v81Verify').forEach(b=>b.onclick=()=>v81Verify(+b.dataset.id));
 if($('verifyProofsBodyV81'))$('verifyProofsBodyV81').innerHTML=creds.filter(c=>c.chain!=='NOT ISSUED').map(c=>`<div class="row-v81"><div><b>${ec(credLabel(c))}</b><div class="small">${ec(userChain(c))}</div></div><button class="sec details" data-id="${c.id}">Open</button></div>`).join('')||'<div class="small">No advanced proof records yet.</div>';document.querySelectorAll('.details').forEach(b=>b.onclick=()=>showProof(+b.dataset.id))}

/* PR 13: the route the registry suggests for a queued credential. */
function queueRouteHtml(c){
 const r=primaryRouteFor(c.kind,c.jurisdiction),floor=kindFloor(c.kind);
 if(!r)return`<div class="small route-v13">Route: no approved registry source yet for this kind. Needs at least ${ec(levelLabel(floor.level))}.</div>`;
 return`<div class="small route-v13">Route: <b>${ec(r.name)}</b> (${ec(VERIFICATION_METHODS[r.method].label)}) → ${ec(levelLabel(sourceLevel(r)))}${r.lookupUrl?` · <a href="${ec(r.lookupUrl)}" target="_blank" rel="noopener">official lookup</a>`:''}</div>`;
}
/* Verification Sources tab: the registry, searchable. */
let regFilterV13='',regTypeV13='';
function renderRegistryV13(){
 const el=$('verifySourcesBodyV13');if(!el)return;
 const t=regFilterV13.trim().toLowerCase();
 const rows=VERIFICATION_SOURCES.filter(s=>(!regTypeV13||s.type===regTypeV13)&&(!t||(s.name+' '+s.jurisdiction+' '+jurisdictionName(s.jurisdiction)+' '+s.kinds.join(' ')).toLowerCase().includes(t)));
 const counts=Object.keys(SOURCE_TYPES).map(k=>[k,VERIFICATION_SOURCES.filter(s=>s.type===k).length]).filter(x=>x[1]);
 el.innerHTML=`<p class="small">Where Veridun accepts a confirmation from, and the trust level each one gives. Checked ${ec(REGISTRY_AS_OF)}. Lookup links are listed only when confirmed on the official site. Upload, self-attestation and AI extraction never count as primary source.</p>
 <div class="grid2-v83"><label>Search<input id="regSearchV13" value="${ec(regFilterV13)}" placeholder="State, board, credential…"></label><label>Type<select id="regTypeV13"><option value="">All types (${VERIFICATION_SOURCES.length})</option>${counts.map(([k,n])=>`<option value="${k}"${regTypeV13===k?' selected':''}>${ec(SOURCE_TYPES[k])} (${n})</option>`).join('')}</select></label></div>
 <div class="small" style="margin:6px 0">Levels: ${VERIFICATION_LEVELS.map(l=>`<span class="lvl-chip-v13" title="${ec(l.desc)}">${ec(l.label)}</span>`).join(' ')}</div>
 <div class="reg-list-v13" id="regListV13">${rows.map(s=>`<details class="reg-row-v13" data-source="${ec(s.id)}"><summary><b>${ec(s.name)}</b> <span class="badge ${s.status==='APPROVED'?'VERIFIED':s.status==='PENDING'?'PENDING':'REVOKED'}">${ec(SOURCE_STATUS[s.status])}</span><div class="small">${ec(SOURCE_TYPES[s.type])}${s.jurisdiction&&s.jurisdiction!=='US'?' · '+ec(jurisdictionName(s.jurisdiction)):s.jurisdiction==='US'?' · US (participating boards)':''} · ${ec(VERIFICATION_METHODS[s.method].label)} → ${ec(sourceLevel(s)?levelLabel(sourceLevel(s)):'no level')}</div></summary>
 <div class="why-grid-v13"><div>Credentials</div><div>${ec(s.kinds.length?s.kinds.slice(0,12).map(k=>catalogKind(k)?.short||k).join(', ')+(s.kinds.length>12?' +'+(s.kinds.length-12)+' more':''):'none')}</div><div>Official lookup</div><div>${s.lookupUrl?`<a href="${ec(s.lookupUrl)}" target="_blank" rel="noopener">${ec(s.lookupUrl)}</a>`:'Not confirmed — none listed'}</div><div>API</div><div>${s.api.available?'Available · ':'None · '}${ec(s.api.requirements)}</div>${s.type==='LICENSING_BOARD'?`<div>Nursys</div><div>${s.nursys?'Participates in QuickConfirm':'Does not participate'}</div>`:''}<div>Notes</div><div>${ec(s.notes||'')}</div></div></details>`).join('')||'<div class="small">No sources match.</div>'}</div>`;
 $('regSearchV13').oninput=e=>{regFilterV13=e.target.value;const pos=e.target.selectionStart;renderRegistryV13();const n=$('regSearchV13');n.focus();n.setSelectionRange(pos,pos)};
 $('regTypeV13').onchange=e=>{regTypeV13=e.target.value;renderRegistryV13()};
}
